name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test

  lighthouse-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Build
      run: yarn build
    - name: Run lighthouse test
        uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: './.lighthouserc.json'