name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Install modules
      run: yarn
    - name: Lint
      run: yarn lint
  
  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Install modules
      run: yarn
    - name: Run unittest
      run: yarn test

  e2etest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Install modules
      run: yarn
    - name: Build
      run: yarn build
    - name: Run e2etest
      run: yarn test:e2e:ci
    - name: Save video
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Cypress videos
        path: cypress/videos

  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Install modules
      run: yarn
    - name: Build
      run: yarn build
    - name: Run lighthouse
      uses: treosh/lighthouse-ci-action@v9
      with:
        temporaryPublicStorage: true
        configPath: './.lighthouserc.json'
